version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333" # Qdrant default port
    volumes:
      - qdrant_storage:/qdrant/storage

  app:
    build: .
    container_name: streamlit_app
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - qdrant
    command: streamlit run src/app.py

volumes:
  qdrant_storage:
